#############################################################################
# Makefile for building: TemplateMatch
# Generated by qmake (2.01a) (Qt 4.8.0) on: Wed May 16 21:51:48 2012
# Project:  SmartHome.pro
# Template: app
# Command: /opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile SmartHome.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -I. -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtNetwork -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include -I/usr/local/include/opencv -I/usr/local/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LIBS          = $(SUBLIBS)  -L/opt/QtSDK/Desktop/Qt/4.8.0/gcc/lib /usr/local/lib/libopencv_core.so.2.3.1 /usr/local/lib/libopencv_imgproc.so.2.3.1 /usr/local/lib/libopencv_highgui.so.2.3.1 /usr/local/lib/libopencv_ml.so.2.3.1 /usr/local/lib/libopencv_video.so.2.3.1 /usr/local/lib/libopencv_features2d.so.2.3.1 /usr/local/lib/libopencv_calib3d.so.2.3.1 /usr/local/lib/libopencv_objdetect.so.2.3.1 /usr/local/lib/libopencv_contrib.so.2.3.1 /usr/local/lib/libopencv_legacy.so.2.3.1 /usr/local/lib/libopencv_flann.so.2.3.1 -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		handdetector.cpp \
		svmhanddetector.cpp \
		simplehanddetector.cpp moc_mainwindow.cpp \
		qrc_tm.cpp
OBJECTS       = main.o \
		mainwindow.o \
		handdetector.o \
		svmhanddetector.o \
		simplehanddetector.o \
		moc_mainwindow.o \
		qrc_tm.o
DIST          = /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		SmartHome.pro
QMAKE_TARGET  = TemplateMatch
DESTDIR       = 
TARGET        = TemplateMatch

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: SmartHome.pro  /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++/qmake.conf /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile SmartHome.pro
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile SmartHome.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TemplateMatch1.0.0 || $(MKDIR) .tmp/TemplateMatch1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TemplateMatch1.0.0/ && $(COPY_FILE) --parents mainwindow.h handdetector.h svmhanddetector.h simplehanddetector.h .tmp/TemplateMatch1.0.0/ && $(COPY_FILE) --parents tm.qrc .tmp/TemplateMatch1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp handdetector.cpp svmhanddetector.cpp simplehanddetector.cpp .tmp/TemplateMatch1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/TemplateMatch1.0.0/ && (cd `dirname .tmp/TemplateMatch1.0.0` && $(TAR) TemplateMatch1.0.0.tar TemplateMatch1.0.0 && $(COMPRESS) TemplateMatch1.0.0.tar) && $(MOVE) `dirname .tmp/TemplateMatch1.0.0`/TemplateMatch1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TemplateMatch1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: simplehanddetector.h \
		handdetector.h \
		mainwindow.h
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_tm.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_tm.cpp
qrc_tm.cpp: tm.qrc \
		hands/0.png \
		hands/1.png \
		hands/2.png \
		hands/3.png \
		hands/4.png \
		hands/5.png \
		hands/6.png \
		hands/7.png \
		hands/8.png \
		hands/9.png
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/rcc -name tm tm.qrc -o qrc_tm.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		simplehanddetector.h \
		handdetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		simplehanddetector.h \
		handdetector.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

handdetector.o: handdetector.cpp handdetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handdetector.o handdetector.cpp

svmhanddetector.o: svmhanddetector.cpp svmhanddetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o svmhanddetector.o svmhanddetector.cpp

simplehanddetector.o: simplehanddetector.cpp simplehanddetector.h \
		handdetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simplehanddetector.o simplehanddetector.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_tm.o: qrc_tm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_tm.o qrc_tm.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

